<!-- Generated by DynamicalWeb (<?php \DynamicalWeb\HTML::print(hash("crc32b", time()) . "-" . hash("sha256", time())); ?>) -->
<!-- Copyright, Intellivoid Technologies -->
<!-- You are supposed to see this if your browser isn't entirely written in JavaScript, keep the web Javascript bloat free! Make fun of all soydevs! -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">

<!-- Favicon -->
<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png?v=alJ0vdleRR">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png?v=alJ0vdleRR">
<link rel="icon" type="image/png" sizes="192x192" href="/assets/favicon/android-chrome-192x192.png?v=alJ0vdleRR">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png?v=alJ0vdleRR">
<link rel="manifest" href="/assets/favicon/site.webmanifest?v=alJ0vdleRR">
<link rel="mask-icon" href="/assets/favicon/safari-pinned-tab.svg?v=alJ0vdleRR" color="#ba00ff">
<link rel="shortcut icon" href="/assets/favicon/favicon.ico?v=alJ0vdleRR">
<meta name="apple-mobile-web-app-title" content="Intellivoid Technlogies">
<meta name="application-name" content="Intellivoid Technlogies">
<meta name="msapplication-TileColor" content="#9f00a7">
<meta name="msapplication-TileImage" content="/assets/favicon/mstile-144x144.png?v=alJ0vdleRR">
<meta name="msapplication-config" content="/assets/favicon/browserconfig.xml?v=alJ0vdleRR">

<!-- Dynamic Theme -->
<?php
    $ThemeColor = "#ffff";
    if(defined("THEME_COLOR"))
        $ThemeColor = THEME_COLOR;
?>
<meta name="theme-color" content="<?PHP \DynamicalWeb\HTML::print($ThemeColor, false); ?>">

<!-- Primary Meta Tags -->
<meta name="title" content="Intellivoid">
<meta name="description" content="Software & Services for consumers and businesses">
<meta property="og:type" content="website">
<meta property="og:url" content="https://intellivoid.net/">
<meta property="og:title" content="Intellivoid">
<meta property="og:description" content="Software & Services for consumers and businesses">
<meta property="og:image" content="/assets/media/banner.jpg">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://intellivoid.net/">
<meta property="twitter:title" content="Intellivoid">
<meta property="twitter:description" content="Software & Services for consumers and businesses">
<meta property="twitter:image" content="/assets/media/banner.jpg">

<!-- General -->
<?PHP \DynamicalWeb\CSS::importStyle("main"); ?>
<link href="/assets/css/all.min.css" rel="stylesheet">
